export const flow1FormInitialValues = {
    fullName: "mahmut mahmut",
    age: "10",
    gender: "erkek",
    email: "adad@gmail.com",
    phone: "5434296967",
    country: "Turkey",
    city: "Istanbul",
    identifiedDiseases: "adadadda",
    currentMedicationsAndTreatments: "adadda",
    usedSupplementsAndTime: "adadadda",
    shortStory: "adada",
    purposeOfMeeting: "addda",
    meetingType: "online",
};
export const flow2FormInitialValues = {
    parrentTolarance: "evet",
    motherMilk: "Bilmiyorum",
    solidFood: "evet",
    babyAllergy: "evet",
    childFoodReact: "bilmiyorum",
    childFoodAccess: "evet",
    childFoodDisorder: "hayır",
    foodDisorder: "29999",
    favoriteFood: "21000",
    mostEatenFood: "21111",
    foodPreparedBy: "21222",
    foodPurchasedBy: "21333",
    cookingFrequency: "21444",
    mostNutritiousFood: "21555",
    leastNutritiousFood: "21666",
    extraInfo: "21777",
    purposeOfFinal: "21888",
}

export const flow3FormInitialValues = {
    name: "Selami Şahin",
    age: "15",
    date: "2023",
    birthDate: "12 ağustos 2000",
    email: "selami@gmail.com",
    address: "dadadadas kşjalkj lksajdlkja",
    city: "samsun",
    phoneCell: 5434354354354,
    geneticHistory: "Diğer",
    geneticHistoryOther: "balkan göçmeni",
    lastHealt: "sdfdfdfdff",
    emergencyContact: "24354534",
    emergencyContactRelation: "sevgili",
    emergencyContactPhoneCell: "4245453464",
    whereDidYouHear: "Üniversiteden",
    whereDidYouHearOther: "dadada",
    currentDisease: [
        {
            problem: "dadadada",
            severity: "dadada",
            treatment: "adadad",
            success: "adadada",
        }
    ],
    allergies: [
        {
            food: "adadda",
            reaction: "dadada",
        }
    ],
    sleepHours: "4",
    sleepDifficulty: "hayır",
    sleepQuality: "evet",
    sleepProblem: "hayır",
    snore: "hayır",
    wakeUp: "hayır",
    sleepPills: "hayır",
    sleepPillsDetail: "hayır",
    diet: [],
    foodSensitivity: "evet",
    foodSensitivityDetail: "yok",
    foodAvoid: "hayır",
    foodAvoidDetail: "",
    foodsReaction: ["diğer"],
    foodsReactionDetail: "yok 2",
    foodsLike: "evet",
    foodsLikeDetail: "yok",
    threeMeal: "hayır",
    threeMealDetail: "dadada",
    skipMeal: "hayır",
    skipMealDetail: "",
    outsideMeal: "6",
    x: ["hızlı yerim"],
    genetikhastaliklar:{

    }
}