export const flow1FormInitialValues = {
    fullName: "mahmut mahmut",
    age: "10",
    gender: "erkek",
    email: "adad@gmail.com",
    phone: "5434296967",
    country: "Turkey",
    city: "Istanbul",
    identifiedDiseases: "adadadda",
    currentMedicationsAndTreatments: "adadda",
    usedSupplementsAndTime: "adadadda",
    shortStory: "adada",
    purposeOfMeeting: "addda",
    meetingType: "online",
};
export const flow2FormInitialValues = {
    parrentTolarance: "evet",
    motherMilk: "Bilmiyorum",
    solidFood: "evet",
    babyAllergy: "evet",
    childFoodReact: "bilmiyorum",
    childFoodAccess: "evet",
    childFoodDisorder: "hayır",
    foodDisorder: "29999",
    favoriteFood: "21000",
    mostEatenFood: "21111",
    foodPreparedBy: "21222",
    foodPurchasedBy: "21333",
    cookingFrequency: "21444",
    mostNutritiousFood: "21555",
    leastNutritiousFood: "21666",
    extraInfo: "21777",
    purposeOfFinal: "21888",
}

export const flow3FormInitialValues = {
    name: "Selami Şahin",
    age: "15",
    date: "2023",
    birthDate: "12 ağustos 2000",
    email: "selami@gmail.com",
    address: "dadadadas kşjalkj lksajdlkja",
    city: "samsun",
    phoneCell: 5434354354354,
    geneticHistory: "Diğer",
    geneticHistoryOther: "balkan göçmeni",
    lastHealt: "sdfdfdfdff",
    emergencyContact: "24354534",
    emergencyContactRelation: "sevgili",
    emergencyContactPhoneCell: "4245453464",
    whereDidYouHear: "Üniversiteden",
    whereDidYouHearOther: "dadada",
    currentDisease: [
        {
            problem: "dadadada",
            severity: "dadada",
            treatment: "adadad",
            success: "adadada",
        }
    ],
    allergies: [
        {
            food: "adadda",
            reaction: "dadada",
        }
    ],
    sleepHours: "4",
    sleepDifficulty: "hayır",
    sleepQuality: "evet",
    sleepProblem: "hayır",
    snore: "hayır",
    wakeUp: "hayır",
    sleepPills: "hayır",
    sleepPillsDetail: "hayır",
    diet: [],
    foodSensitivity: "evet",
    foodSensitivityDetail: "yok",
    foodAvoid: "hayır",
    foodAvoidDetail: "",
    foodsReaction: ["diğer"],
    foodsReactionDetail: "yok 2",
    foodsLike: "evet",
    foodsLikeDetail: "yok",
    threeMeal: "hayır",
    threeMealDetail: "dadada",
    skipMeal: "hayır",
    skipMealDetail: "",
    outsideMeal: "6",
    x: ["hızlı yerim"],
    genetikhastaliklar: {}
}


export const flow4FormInitialValues = {
    headAche: 0,
    headDizziness: 0,
    headNausea: 0,
    headSleeplessness: 0,
    eyeWatering: 0,
    eyeSwelling: 0,
    eyePuffiness: 0,
    eyeBlurryVision: 0,
    earItching: 0,
    earPain: 0,
    earDischarge: 0,
    earRinging: 0,
    noseCongestion: 0,
    noseSinus: 0,
    noseAllergy: 0,
    noseSneezing: 0,
    noseMucus: 0,
    mouthCough: 0,
    mouthCleaning: 0,
    mouthPain: 0,
    mouthSwelling: 0,
    mouthCotton: 0,
    skinAcne: 0,
    skinRash: 0,
    skinItching: 0,
    skinBaldness: 0,
    skinSweating: 0,
    heartIrregularity: 0,
    heartFast: 0,
    heartChestPain: 0,
    lungCongestion: 0,
    lungAsthma: 0,
    lungShortnessOfBreath: 0,
    lungBreathingDifficulties: 0,
    digestiveNausea: 0,
    digestiveDiarrhea: 0,
    digestiveConstipation: 0,
    digestiveBloating: 0,
    digestiveGas: 0,
    digestiveBurning: 0,
    digestiveStomachPain: 0,
    jointsPain: 0,
    jointsArthritis: 0,
    jointsStiffness: 0,
    jointsMusclePain: 0,
    jointsFatigue: 0,
    weightOvereating: 0,
    weightCraving: 0,
    weightObesity: 0,
    weightImpulseEating: 0,
    weightWaterRetention: 0,
    weightWeightLoss: 0,
    energyLethargy: 0,
    energyApathy: 0,
    energyHyperactivity: 0,
    energyRestlessness: 0,
    mindMemory: 0,
    mindUnderstanding: 0,
    mindConcentration: 0,
    mindPhysicalCoordination: 0,
    mindDecisionMaking: 0,
    mindDizziness: 0,
    mindSpeech: 0,
    mindLearning: 0,
    emotionalVibration: 0,
    emotionalObsession: 0,
    emotionalAngry: 0,
    emotionalDepression: 0,
    otherFrequentIllness: 0,
    otherFrequentUrination: 0,
    otherGenitalItching: 0,
}


export const flow5FormInitialValues = {
    headAche: 0,
    headDizziness: 0,
    headNausea: 0,
    headSleeplessness: 0,
    eyeWatering: 0,
    eyeSwelling: 0,
    eyePuffiness: 0,
    eyeBlurryVision: 0,
    earItching: 0,
    earPain: 0,
    earDischarge: 0,
    earRinging: 0,
    noseCongestion: 0,
    noseSinus: 0,
    noseAllergy: 0,
    noseSneezing: 0,
    noseMucus: 0,
    mouthCough: 0,
    mouthCleaning: 0,
    mouthPain: 0,
    mouthSwelling: 0,
    mouthCotton: 0,
    skinAcne: 0,
    skinRash: 0,
    skinItching: 0,
    skinBaldness: 0,
    skinSweating: 0,
    heartIrregularity: 0,
    heartFast: 0,
    heartChestPain: 0,
    lungCongestion: 0,
    lungAsthma: 0,
    lungShortnessOfBreath: 0,
    lungBreathingDifficulties: 0,
    digestiveNausea: 0,
    digestiveDiarrhea: 0,
    digestiveConstipation: 0,
    digestiveBloating: 0,
    digestiveGas: 0,
    digestiveBurning: 0,
    digestiveStomachPain: 0,
    jointsPain: 0,
    jointsArthritis: 0,
    jointsStiffness: 0,
    jointsMusclePain: 0,
    jointsFatigue: 0,
    weightOvereating: 0,
    weightCraving: 0,
    weightObesity: 0,
    weightImpulseEating: 0,
    weightWaterRetention: 0,
    weightWeightLoss: 0,
    energyLethargy: 0,
    energyApathy: 0,
    energyHyperactivity: 0,
    energyRestlessness: 0,
    mindMemory: 0,
    mindUnderstanding: 0,
    mindConcentration: 0,
    mindPhysicalCoordination: 0,
    mindDecisionMaking: 0,
    mindDizziness: 0,
    mindSpeech: 0,
    mindLearning: 0,
    emotionalVibration: 0,
    emotionalObsession: 0,
    emotionalAngry: 0,
    emotionalDepression: 0,
    otherFrequentIllness: 0,
    otherFrequentUrination: 0,
    otherGenitalItching: 0,
    textLast2Week:"ııı",
    textLifeStyleChange:"xx",
    textHaveAProblem: "yy",
    textSomethingElse:"zz"
}