export const flow1FormInitialValues = {
    fullName: "mahmut mahmut",
    age: "10",
    gender: "erkek",
    email: "adad@gmail.com",
    phone: "5434296967",
    country: "Turkey",
    city: "Istanbul",
    identifiedDiseases: "adadadda",
    currentMedicationsAndTreatments: "adadda",
    usedSupplementsAndTime: "adadadda",
    shortStory: "adada",
    purposeOfMeeting: "addda",
    meetingType: "online",
};
export const flow2FormInitialValues = {
    parrentTolarance: "evet",
    parrentTolaranceDesc: "açıklama",
    motherMilk: "Bilmiyorum",
    motherMilkDesc: "6 ay",
    motherMilkDesc1: "bebelac",
    solidFood: "evet",
    solidFoodDesc: "12",
    babyAllergy: "evet",
    childFoodReact: "bilmiyorum",
    childFoodReactDesc: "açıklama",
    childFoodAccess: "evet",
    childFoodDisorder: "hayır",
    childFoodDisorderDesc: "test",
    foodDisorder: "29999",
    foodDisorderDesc: "test",
    favoriteFood: "21000",
    mostEatenFood: "21111",
    foodPreparedBy: "21222",
    foodPurchasedBy: "21333",
    cookingFrequency: "21444",
    mostNutritiousFood: "21555",
    leastNutritiousFood: "21666",
    extraInfo: "21777",
    purposeOfFinal: "21888",
}

export const flow3FormInitialValues = {
    motherMilk: "Bilmiyorum",
    motherMilkDesc: "6 ay",
    motherMilkDesc1: "bebelac",
    name: "Selami Şahin",
    age: "15",
    birthDate: "12 ağustos 2000",
    email: "selami@gmail.com",
    address: "dadadadas kşjalkj lksajdlkja",
    city: "samsun",
    phoneCell: 5434354354354,
    lastHealt: "sdfdfdfdff",
    emergencyContact: "24354534",
    emergencyContactRelation: "sevgili",
    emergencyContactPhoneCell: "4245453464",
    emergencyContactPhoneCellHome: "4245453464",
    emergencyContactPhoneCellWork: "4245453464",
    whereDidYouHear: "Üniversiteden",
    whereDidYouHearOther: "dadada",
    currentDisease: [
        {
            problem: "dadadada",
            severity: "dadada",
            treatment: "adadad",
            success: "adadada",
        }
    ],
    allergies: [
        {
            food: "adadda",
            reaction: "dadada",
        }
    ],
    sleepHours: "4",
    sleepDifficulty: "hayır",
    sleepQuality: "evet",
    sleepProblem: "hayır",
    snore: "hayır",
    wakeUp: "hayır",
    sleepPills: "hayır",
    sleepPillsDetail: "uyku ilacı adı",
    exercise: "asdasd",

    //EGZ 
    egz1E: "qwer",
    egz1H: "trw",
    egz1S: "lnll",
    
    egz2E: "qwer",
    egz2H: "trw",
    egz2S: "lnll",

    egz3E: "qwer",
    egz3H: "trw",
    egz3S: "lnll",

    egz4E: "qwer",
    egz4H: "trw",
    egz4S: "lnll",

    egz5E: "qwer",
    egz5H: "trw",
    egz5S: "lnll",

    egz6E: "qwer",
    egz6H: "trw",
    egz6S: "lnll",
    //EGZ

    exerciseWant: "evet",
    exerciseDisability: "evet",
    exerciseDisabilityDesc: "test",
    exerciseLater: "evet",
    exerciseLaterDesc: "asdasd",
    diet: [],
    dietDesc: "diet desc",
    foodSensitivity: "evet",
    foodSensitivityDetail: "yok",
    foodAvoid: "hayır",
    foodAvoidDetail: "xxx",
    foodsReaction: ["diğer"],
    foodsReactionDetail: "yok 2",
    foodsLike: "evet",
    foodsLikeDetail: "yok",
    threeMeal: "hayır",
    threeMealDetail: "dadada",
    skipMeal: "hayır",
    skipMealDetail: "al sana detay",
    outsideMeal: "1-3",
    lifestyleAboutEating: ["çok yerim"],
    currentDiet: ["vejetaryan"],
    genetikhastaliklar: {

    },
    currentDietOther: "asdasd",
    breakfast: "teasd",
    lunch: "asd",
    dinner: "asda",
    snacks: "asdas",
    beverages: "asdsa",
    fruit: "2",
    vegetable: "2",
    legumes: "2",
    redMeat: "3",
    fish: "3",
    dairyProducts: "3",
    nutsAndSeeds: "4",
    oil: "1",
    cannedDrink: "3",
    dessert: "1",
    caffeinatedBeverage: "evet",
    caffeinatedBeverageYes: "asdasd",
    coffeQuantity: "1",
    teaQuantity: "2-4",
    carbonatedCoffeeQuantity: ">4",
    caffeineReaction: "evet",
    caffeineReactionDesc: "ölüyomm",
    caffeineSensation: ["ağrı"],
    smoke: "evet",
    smokeType: ["sigara"],
    smokeQuantity: "2",
    smokeYear: "3",
    smokeBlock: "evet",
    smokeBlockDesc: "asdas",
    oldSmoke: "evet",
    oldSmokeQuantity: "1",
    oldSmokeYear: "2",
    cigaretteSmoke: "evet",
    alcoholWeek: "1-3",
    oldAlcohol: "evet",
    oldAlcoholProblems: "evet",
    oldAlcoholProblemsWhatTime: "dün",
    oldAlcoholProblemsDesc: "krize giriyodum",
    oldAlcoholProblemsHelp: "evet",
    recreationalDrug: "evet",
    recreationalDrugDesc: "evasd",
    inhaledSubstance: "hayır",
    stress: "evet",
    copeWithStress: "hayır",
    workStress: "1",
    familyStress: "2",
    healtyStress: "3",
    socialStress: "4",
    materialStress: "5",
    otherStress: "6",
    relaxationTechniques: "evet",
    relaxationTechniquesDesc: "Haftada bir",
    techniques: ["diğer"],
    techniquesDesc: "dasds",
    consultancy: "evet",
    therapy: "evet",
    therapyDesc: "adasd",
    molestation: "hayır",
    hobbies: "al sana hobi",
    maritalStatus: "bekar",
    liveWith: "annem babamla",
    job: "doktor",
    oldJob: "tezgahtar",
    emotionalSupport: "evet",
    emotionalSupportSelect: ["aile"],
    emotionalSupportOther: "asdas",
    general: "1",
    school: "1",
    businessLife: "1",
    socialLife: "1",
    bestFriend: "1",
    sexuality: "1",
    position: "1",
    withBoyFriendAndGirlFriend: "1",
    children: "1",
    parents: "1",
    partner: "1",
    birth: "premature",
    birthComplication: "evet",
    birthComplicationDesc: "asdasda",



    solidFoods: "11",
    wheat: "22",
    dairy: "33",
    avoidedFood: "evet",
    sugarOrSweet: "evet",
    silverMercuryFiller: "evet",
    silverMercuryFillerDesc: "1",
    GoldFiller: "evet",
    GoldFillerDesc: "2",
    rootCanalTreatment: "evet",
    rootCanalTreatmentDesc: "1",
    Implant: "evet",
    ImplantDesc: "2",
    platingMetal: "evet",
    platingMetalDesc: "4",
    toothache: "evet",
    toothacheDesc: "1",
    bleedingGums: "evet",
    bleedingGumsDesc: "1",
    gumProblem: "evet",
    gumProblemDesc: "2",
    chewingProblems: "evet",
    chewingProblemsDesc: "1",
    otherDentalProblems: "evet",
    otherDentalProblemsDesc: "2",
    removingYourMercuryFiller: "evet",
    removingYourMercuryFillerDesc: "adasdas",
    howManyFillersAsAChild: "1",
    brushingTeeth: "evet",
    floss: "evet",
    affectsYouSignificantly: ["diğer"],
    affectsYouSignificantlyDesc: "mazot",
    exposedToAtWorkOrAtHome: ["boya", "diğer"],
    exposedToAtWorkOrAtHomeDesc: "dadas",
    significantExposureToHarmfulChemical: "evet",
    significantExposureToHarmfulChemicalDesc: "textasdasd",
    petOrFarmAnimal: "evet",
    petOrFarmAnimalDesc: "içerde",
    suitablePartsForYou: ["sertleşmeme", "gece idrara çıkma", "cinsel yol ile bulaşan hastalık"],
    suitablePartsForYouPeeDesc: "2",
    suitablePartsForYouSexualDesc: "asdasd",
    psa: "evet",
    psaValue: "2-4",
    otherTest: "asasdasdasdas",
    pregnancy: "evet",
    pregnancyCount: "1",
    low: "evet",
    lowCount: "2",
    abortion: "evet",
    abortionCount: "1",
    livingChild: "evet",
    livingChildCount: "3",
    naturalChildbirth: "evet",
    naturalChildbirthCount: "1",
    cesareanDelivery: "evet",
    cesareanDeliveryCount: "3",
    birthdayOnTheDay: "evet",
    birthdayOnTheDayCount: "4",
    premature: "evet",
    prematureCount: "1",
    bigbaby: "hayır",
    bigbabyCount: "0",
    smallbaby: "hayır",
    smallbabyCount: "0",
    postPregnancyProblems: "evet",
    postPregnancyProblemsDesc: "asdasd",
    firstMenstrualAge: "33",
    lastMenstrualAge: "29/05/1997",
    menstruationInterval: "18",
    menstrualPeriod: "3",
    menstrualCramp: "evet",
    menstrualPain: "evet",
    menstrualProblems: "evet",
    menstrualProblemsDesc: "sinirlilik",
    lastMenstrualProblems: "kanama",
    lastMenstrualProblemsDesc: "fena",
    hormonalBirthControl: "evet",
    hormonalBirthControlDesc: "olmadı",
    anotherMethod: "evet",
    anotherMethods: ["kondom", "spiral"],
    IsMenopause: "hayır",
    MenopauseLastedAge: "44",
    surgicalMenopause: "hayır",
    surgicalMenopauseDesc: "kaza oldu",
    menopauseComplaints: ["başağrısı"],
    hormoneTherapy: "evet",
    hormoneTherapyDesc: "güzel gidiyo",
    gynecologicalSymptoms: ["endometriyozis", "myom", "cinsel yol ile bulaşan hastalık (açıklayınız)"],
    gynecologicalSymptomsDesc: "virüs",
    smearTest: "evet",
    smearTestResponse: "kötü",
    mammographyTest: "evet",
    mammographyTestResponse: "berbat",
    bone: "evet",
    boneResponse: "normal",
    otherTestWomen: "valla baika test yaptırmadım",
    anotherTest: "evet",
    anotherTestDesc: "sdasdasdasda",
    // medicalResumeDigestionQuestion 6
    medicalResumeDigestionQuestion1: "evet",
    medicalResumeDigestionQuestion2: "evet",
    medicalResumeDigestionQuestion3: "evet",
    medicalResumeDigestionQuestion4: "hayır",
    medicalResumeDigestionQuestion5: "evet",
    medicalResumeDigestionQuestion6: "evet",
    // medicalResumeBreathingQuestion 6
    medicalResumeBreathingQuestion1: "evet",
    medicalResumeBreathingQuestion2: "önce",
    medicalResumeBreathingQuestion3: "evet",
    medicalResumeBreathingQuestion4: "evet",
    medicalResumeBreathingQuestion5: "evet",
    medicalResumeBreathingQuestion6: "evet",
    // medicalResumeGenitalQuestion 7
    medicalResumeGenitalQuestion1: "önce",
    medicalResumeGenitalQuestion2: "hayır",
    medicalResumeGenitalQuestion3: "hayır",
    medicalResumeGenitalQuestion4: "hayır",
    medicalResumeGenitalQuestion5: "hayır",
    medicalResumeGenitalQuestion6: "hayır",
    medicalResumeGenitalQuestion7: "hayır",
    //medicalResumeMetabolicQuestion 7
    medicalResumeMetabolicQuestion1: "evet",
    medicalResumeMetabolicQuestion2: "evet",
    medicalResumeMetabolicQuestion3: "evet",
    medicalResumeMetabolicQuestion4: "evet",
    medicalResumeMetabolicQuestion5: "evet",
    medicalResumeMetabolicQuestion6: "evet",
    medicalResumeMetabolicQuestion7: "evet",
    //medicalResumeInflammatoryQuestion 9
    medicalResumeInflammatoryQuestion1: "önce",
    medicalResumeInflammatoryQuestion2: "önce",
    medicalResumeInflammatoryQuestion3: "önce",
    medicalResumeInflammatoryQuestion4: "önce",
    medicalResumeInflammatoryQuestion5: "önce",
    medicalResumeInflammatoryQuestion6: "önce",
    medicalResumeInflammatoryQuestion7: "önce",
    medicalResumeInflammatoryQuestion8: "önce",
    medicalResumeInflammatoryQuestion9: "önce",
    //medicalResumeMusculoskeletalQuestion 3
    medicalResumeMusculoskeletalQuestion1: "evet",
    medicalResumeMusculoskeletalQuestion2: "evet",
    medicalResumeMusculoskeletalQuestion3: "evet",
    //medicalResumeLeatherQuestion 4
    medicalResumeLeatherQuestion1: "önce",
    medicalResumeLeatherQuestion2: "önce",
    medicalResumeLeatherQuestion3: "önce",
    medicalResumeLeatherQuestion4: "önce",

    //medicalResumeHeartQuestion 10
    medicalResumeHeartQuestion1: "hayır",
    medicalResumeHeartQuestion2: "hayır",
    medicalResumeHeartQuestion3: "hayır",
    medicalResumeHeartQuestion4: "hayır",
    medicalResumeHeartQuestion5: "hayır",
    medicalResumeHeartQuestion6: "hayır",
    medicalResumeHeartQuestion7: "hayır",
    medicalResumeHeartQuestion8: "hayır",
    medicalResumeHeartQuestion9: "hayır",
    medicalResumeHeartQuestion10: "hayır",
    //medicalResumeNeurologicalQuestion 10
    medicalResumeNeurologicalQuestion1: "evet",
    medicalResumeNeurologicalQuestion2: "evet",
    medicalResumeNeurologicalQuestion3: "evet",
    medicalResumeNeurologicalQuestion4: "evet",
    medicalResumeNeurologicalQuestion5: "evet",
    medicalResumeNeurologicalQuestion6: "evet",
    medicalResumeNeurologicalQuestion7: "evet",
    medicalResumeNeurologicalQuestion8: "evet",
    medicalResumeNeurologicalQuestion9: "evet",
    medicalResumeNeurologicalQuestion10: "evet",
    //medicalResumeCancerQuestion 5
    medicalResumeCancerQuestion1: "önce",
    medicalResumeCancerQuestion2: "önce",
    medicalResumeCancerQuestion3: "önce",
    medicalResumeCancerQuestion4: "önce",
    medicalResumeCancerQuestion5: "önce",


    //examinationOfSymptomsGeneralQuestion 13
    examinationOfSymptomsGeneralQuestion1: "orta",
    examinationOfSymptomsGeneralQuestion2: "orta",
    examinationOfSymptomsGeneralQuestion3: "orta",
    examinationOfSymptomsGeneralQuestion4: "orta",
    examinationOfSymptomsGeneralQuestion5: "orta",
    examinationOfSymptomsGeneralQuestion6: "orta",
    examinationOfSymptomsGeneralQuestion7: "orta",
    examinationOfSymptomsGeneralQuestion8: "orta",
    examinationOfSymptomsGeneralQuestion9: "orta",
    examinationOfSymptomsGeneralQuestion10: "orta",
    examinationOfSymptomsGeneralQuestion11: "orta",
    examinationOfSymptomsGeneralQuestion12: "orta",
    examinationOfSymptomsGeneralQuestion13: "orta",
    //examinationOfSymptomsEyesAndEarQuestion 14
    examinationOfSymptomsEyesAndEarQuestion1: "hafif",
    examinationOfSymptomsEyesAndEarQuestion2: "hafif",
    examinationOfSymptomsEyesAndEarQuestion3: "hafif",
    examinationOfSymptomsEyesAndEarQuestion4: "hafif",
    examinationOfSymptomsEyesAndEarQuestion5: "hafif",
    examinationOfSymptomsEyesAndEarQuestion6: "hafif",
    examinationOfSymptomsEyesAndEarQuestion7: "hafif",
    examinationOfSymptomsEyesAndEarQuestion8: "hafif",
    examinationOfSymptomsEyesAndEarQuestion9: "hafif",
    examinationOfSymptomsEyesAndEarQuestion10: "hafif",
    examinationOfSymptomsEyesAndEarQuestion11: "hafif",
    examinationOfSymptomsEyesAndEarQuestion12: "hafif",
    examinationOfSymptomsEyesAndEarQuestion13: "hafif",
    examinationOfSymptomsEyesAndEarQuestion14: "hafif",
    //examinationOfSymptomsSkeletonQuestion 19
    examinationOfSymptomsSkeletonQuestion1: "orta",
    examinationOfSymptomsSkeletonQuestion2: "orta",
    examinationOfSymptomsSkeletonQuestion3: "orta",
    examinationOfSymptomsSkeletonQuestion4: "orta",
    examinationOfSymptomsSkeletonQuestion5: "orta",
    examinationOfSymptomsSkeletonQuestion6: "orta",
    examinationOfSymptomsSkeletonQuestion7: "orta",
    examinationOfSymptomsSkeletonQuestion8: "orta",
    examinationOfSymptomsSkeletonQuestion9: "orta",
    examinationOfSymptomsSkeletonQuestion10: "orta",
    examinationOfSymptomsSkeletonQuestion11: "orta",
    examinationOfSymptomsSkeletonQuestion12: "orta",
    examinationOfSymptomsSkeletonQuestion13: "orta",
    examinationOfSymptomsSkeletonQuestion14: "orta",
    examinationOfSymptomsSkeletonQuestion15: "orta",
    examinationOfSymptomsSkeletonQuestion16: "orta",
    examinationOfSymptomsSkeletonQuestion17: "orta",
    examinationOfSymptomsSkeletonQuestion18: "orta",
    examinationOfSymptomsSkeletonQuestion19: "orta",
    //examinationOfSymptomsNervesQuestion 25
    examinationOfSymptomsNervesQuestion1: "şiddetli",
    examinationOfSymptomsNervesQuestion2: "şiddetli",
    examinationOfSymptomsNervesQuestion3: "şiddetli",
    examinationOfSymptomsNervesQuestion4: "şiddetli",
    examinationOfSymptomsNervesQuestion5: "şiddetli",
    examinationOfSymptomsNervesQuestion6: "şiddetli",
    examinationOfSymptomsNervesQuestion7: "şiddetli",
    examinationOfSymptomsNervesQuestion8: "şiddetli",
    examinationOfSymptomsNervesQuestion9: "şiddetli",
    examinationOfSymptomsNervesQuestion10: "şiddetli",
    examinationOfSymptomsNervesQuestion11: "şiddetli",
    examinationOfSymptomsNervesQuestion12: "şiddetli",
    examinationOfSymptomsNervesQuestion13: "şiddetli",
    examinationOfSymptomsNervesQuestion14: "şiddetli",
    examinationOfSymptomsNervesQuestion15: "şiddetli",
    examinationOfSymptomsNervesQuestion16: "şiddetli",
    examinationOfSymptomsNervesQuestion17: "şiddetli",
    examinationOfSymptomsNervesQuestion18: "şiddetli",
    examinationOfSymptomsNervesQuestion19: "şiddetli",
    examinationOfSymptomsNervesQuestion20: "şiddetli",
    examinationOfSymptomsNervesQuestion21: "şiddetli",
    examinationOfSymptomsNervesQuestion22: "şiddetli",
    examinationOfSymptomsNervesQuestion23: "şiddetli",
    examinationOfSymptomsNervesQuestion24: "şiddetli",
    examinationOfSymptomsNervesQuestion25: "şiddetli",


    //examinationOfSymptomsHeartQuestion 11
    examinationOfSymptomsHeartQuestion1: "hafif",
    examinationOfSymptomsHeartQuestion2: "hafif",
    examinationOfSymptomsHeartQuestion3: "hafif",
    examinationOfSymptomsHeartQuestion4: "hafif",
    examinationOfSymptomsHeartQuestion5: "hafif",
    examinationOfSymptomsHeartQuestion6: "hafif",
    examinationOfSymptomsHeartQuestion7: "hafif",
    examinationOfSymptomsHeartQuestion8: "hafif",
    examinationOfSymptomsHeartQuestion9: "hafif",
    examinationOfSymptomsHeartQuestion10: "hafif",
    examinationOfSymptomsHeartQuestion11: "hafif",
    //examinationOfSymptomsPeeQuestion 10
    examinationOfSymptomsPeeQuestion1: "şiddetli",
    examinationOfSymptomsPeeQuestion2: "şiddetli",
    examinationOfSymptomsPeeQuestion3: "şiddetli",
    examinationOfSymptomsPeeQuestion4: "şiddetli",
    examinationOfSymptomsPeeQuestion5: "şiddetli",
    examinationOfSymptomsPeeQuestion6: "şiddetli",
    examinationOfSymptomsPeeQuestion7: "şiddetli",
    examinationOfSymptomsPeeQuestion8: "şiddetli",
    examinationOfSymptomsPeeQuestion9: "şiddetli",
    examinationOfSymptomsPeeQuestion10: "şiddetli",

    //examinationOfSymptomsDigestionQuestion 38
    examinationOfSymptomsDigestionQuestion1: "orta",
    examinationOfSymptomsDigestionQuestion2: "orta",
    examinationOfSymptomsDigestionQuestion3: "orta",
    examinationOfSymptomsDigestionQuestion4: "orta",
    examinationOfSymptomsDigestionQuestion5: "orta",
    examinationOfSymptomsDigestionQuestion6: "orta",
    examinationOfSymptomsDigestionQuestion7: "orta",
    examinationOfSymptomsDigestionQuestion8: "orta",
    examinationOfSymptomsDigestionQuestion9: "orta",
    examinationOfSymptomsDigestionQuestion10: "orta",
    examinationOfSymptomsDigestionQuestion11: "orta",
    examinationOfSymptomsDigestionQuestion12: "orta",
    examinationOfSymptomsDigestionQuestion13: "orta",
    examinationOfSymptomsDigestionQuestion14: "orta",
    examinationOfSymptomsDigestionQuestion15: "orta",
    examinationOfSymptomsDigestionQuestion16: "orta",
    examinationOfSymptomsDigestionQuestion17: "orta",
    examinationOfSymptomsDigestionQuestion18: "orta",
    examinationOfSymptomsDigestionQuestion19: "orta",
    examinationOfSymptomsDigestionQuestion20: "orta",
    examinationOfSymptomsDigestionQuestion21: "orta",
    examinationOfSymptomsDigestionQuestion22: "orta",
    examinationOfSymptomsDigestionQuestion23: "orta",
    examinationOfSymptomsDigestionQuestion24: "orta",
    examinationOfSymptomsDigestionQuestion25: "orta",
    examinationOfSymptomsDigestionQuestion26: "orta",
    examinationOfSymptomsDigestionQuestion27: "orta",
    examinationOfSymptomsDigestionQuestion28: "orta",
    examinationOfSymptomsDigestionQuestion29: "orta",
    examinationOfSymptomsDigestionQuestion30: "orta",
    examinationOfSymptomsDigestionQuestion31: "orta",
    examinationOfSymptomsDigestionQuestion32: "orta",
    examinationOfSymptomsDigestionQuestion33: "orta",
    examinationOfSymptomsDigestionQuestion34: "orta",
    examinationOfSymptomsDigestionQuestion35: "orta",
    examinationOfSymptomsDigestionQuestion36: "orta",
    examinationOfSymptomsDigestionQuestion37: "orta",
    examinationOfSymptomsDigestionQuestion38: "orta",
    //another tests 130
    anotherTest1: "hafif",
    anotherTest2: "hafif",
    anotherTest3: "hafif",
    anotherTest4: "hafif", anotherTest5: "hafif",
    anotherTest6: "hafif", anotherTest7: "hafif",
    anotherTest8: "hafif", anotherTest9: "hafif",
    anotherTest10: "hafif", anotherTest11: "hafif",
    anotherTest12: "hafif", anotherTest13: "hafif",
    anotherTest14: "hafif", anotherTest15: "hafif",
    anotherTest16: "hafif", anotherTest17: "hafif",
    anotherTest18: "hafif", anotherTest19: "hafif",
    anotherTest20: "hafif", anotherTest21: "hafif",
    anotherTest22: "hafif", anotherTest23: "hafif",
    anotherTest24: "hafif", anotherTest25: "hafif",
    anotherTest26: "hafif", anotherTest27: "hafif",
    anotherTest28: "hafif", anotherTest29: "hafif",
    anotherTest30: "hafif", anotherTest31: "hafif",
    anotherTest32: "hafif", anotherTest33: "hafif",
    anotherTest34: "hafif", anotherTest35: "hafif",
    anotherTest36: "hafif", anotherTest37: "hafif",
    anotherTest38: "hafif", anotherTest39: "hafif",
    anotherTest40: "hafif", anotherTest41: "hafif",
    anotherTest42: "hafif", anotherTest43: "hafif",
    anotherTest44: "hafif", anotherTest45: "hafif",
    anotherTest46: "hafif", anotherTest47: "hafif",
    anotherTest48: "hafif", anotherTest49: "hafif",
    anotherTest50: "hafif", anotherTest51: "hafif",
    anotherTest52: "hafif", anotherTest53: "hafif",
    anotherTest54: "hafif", anotherTest55: "hafif",
    anotherTest56: "hafif", anotherTest57: "hafif",
    anotherTest58: "hafif", anotherTest59: "hafif",
    anotherTest60: "hafif", anotherTest61: "hafif",
    anotherTest62: "hafif", anotherTest63: "hafif",
    anotherTest64: "hafif", anotherTest65: "hafif",
    anotherTest66: "hafif", anotherTest67: "hafif",
    anotherTest68: "hafif", anotherTest69: "hafif",
    anotherTest70: "hafif", anotherTest71: "hafif",
    anotherTest72: "hafif", anotherTest73: "hafif",
    anotherTest74: "hafif", anotherTest75: "hafif",
    anotherTest76: "hafif", anotherTest77: "hafif",
    anotherTest78: "hafif", anotherTest79: "hafif",
    anotherTest80: "hafif", anotherTest81: "hafif",
    anotherTest82: "hafif", anotherTest83: "hafif",
    anotherTest84: "hafif", anotherTest85: "hafif",
    anotherTest86: "hafif", anotherTest87: "hafif",
    anotherTest88: "hafif", anotherTest89: "hafif",
    anotherTest90: "hafif", anotherTest91: "hafif",
    anotherTest92: "hafif", anotherTest93: "hafif",
    anotherTest94: "hafif", anotherTest95: "hafif",
    anotherTest96: "hafif", anotherTest97: "hafif",
    anotherTest98: "hafif", anotherTest99: "hafif",
    anotherTest100: "hafif", anotherTest101: "hafif",
    anotherTest102: "hafif", anotherTest103: "hafif",
    anotherTest104: "hafif", anotherTest105: "hafif",
    anotherTest106: "hafif", anotherTest107: "hafif",
    anotherTest108: "hafif", anotherTest109: "hafif",
    anotherTest110: "hafif", anotherTest111: "hafif",
    anotherTest112: "hafif", anotherTest113: "hafif",
    anotherTest114: "hafif", anotherTest115: "hafif",
    anotherTest116: "hafif", anotherTest117: "hafif",
    anotherTest118: "hafif", anotherTest119: "hafif",
    anotherTest120: "hafif", anotherTest121: "hafif",
    anotherTest122: "hafif", anotherTest123: "hafif",
    anotherTest124: "hafif", anotherTest125: "hafif",
    anotherTest126: "hafif", anotherTest127: "hafif",
    anotherTest128: "hafif", anotherTest129: "şiddetli",
    anotherTest130: "şiddetli",
    anotherTest131: "3",
    anotherTest132: "3",
    anotherTest133: "2",
    anotherTest134: "1",
    anotherTest135: "3",
    anotherTest136: "2",
    anotherTest137: "5",
    anotherTest138: "orta",
    anotherTest139: "1",
    anotherTest140: "2",
    anotherTest141: "orta",
    anotherTest142: "orta",
    anotherTest143: "orta",
    anotherTest144: "orta",
    anotherTest145: "orta",
    anotherTest146: "orta",
    anotherTest147: "orta",
    anotherTest148: "orta",
    anotherTest149: "orta",
    anotherTest150: "orta",
    //TOG 
    tog1Date: "2023-02-18",
    tog1Result: "tog1 result",
    tog2Date: "2023-02-18",
    tog2Result: "tog2 result",
    tog3Date: "2023-02-18",
    tog3Result: "tog3 result",
    tog4Date: "2023-02-18",
    tog4Result: "tog4 result",
    tog5Date: "2023-02-18",
    tog5Result: "tog5 result",
    tog6Date: "2023-02-18",
    tog6Result: "tog6 result",
    tog7Date: "2023-02-18",
    tog7Result: "tog7 result",
    tog8Date: "2023-02-18",
    tog8Result: "tog8 result",
    tog9Date: "2023-02-18",
    tog9Result: "tog9 result",
    tog10Date: "2023-02-18",
    tog10Result: "tog10 result",
    tog11Date: "2023-02-18",
    tog11Result: "tog11 result",
    tog12Date: "2023-02-18",
    tog12Result: "tog12 result",
    //TOG END
    //TOGY
    togy1Date: "2023-02-18",
    togy1Result: "togy1 result",
    togy2Date: "2023-02-18",
    togy2Result: "togy2 result",
    togy3Date: "2023-02-18",
    togy3Result: "togy3 result",
    togy4Date: "2023-02-18",
    togy4Result: "togy4 result",
    togy5Date: "2023-02-18",
    togy5Result: "togy5 result",
    //TOGY END
    //TOGA
    toga1Date: "2023-02-18",
    toga1Result: "toga1 result",
    toga2Date: "2023-02-18",
    toga2Result: "toga2 result",
    toga3Date: "2023-02-18",
    toga3Result: "toga3 result",
    toga4Date: "2023-02-18",
    toga4Result: "toga4 result",
    toga5Date: "2023-02-18",
    toga5Result: "toga5 result",
    toga6Date: "2023-02-18",
    toga6Result: "toga6 result",
    toga7Date: "2023-02-18",
    toga7Result: "toga7 result",
    toga8Date: "2023-02-18",
    toga8Result: "toga8 result",
    //TOGA END
    //TOGh
    togh1Title: "togh1 title",
    togh1Date: "2023-02-18",
    togh1Result: "togh1 result",
    togh2Title: "togh2 title",
    togh2Date: "2023-02-18",
    togh2Result: "togh2 result",
    togh3Title: "togh3 x title",
    togh3Date: "1999-02-14",
    togh3Result: "togh3 sss result",
    togh4Title: "togh4 title",
    togh4Date: "1999-02-14",
    togh4Result: "togh4 result",
    //TOGh END

    // hkitp Pill,Dose,Time,Why string 1 to 6
    hkitp1Pill: "hkitp1Pill",
    hkitp1Dose: "hkitp1Dose",
    hkitp1Time: "hkitp1Time",
    hkitp1Why: "hkitp1Why",
    hkitp2Pill: "hkitp2Pill",
    hkitp2Dose: "hkitp2Dose",
    hkitp2Time: "hkitp2Time",
    hkitp2Why: "hkitp2Why",
    hkitp3Pill: "hkitp3Pill",
    hkitp3Dose: "hkitp3Dose",
    hkitp3Time: "hkitp3Time",
    hkitp3Why: "hkitp3Why",
    hkitp4Pill: "hkitp4Pill",
    hkitp4Dose: "hkitp4Dose",
    hkitp4Time: "hkitp4Time",
    hkitp4Why: "hkitp4Why",
    hkitp5Pill: "hkitp5Pill",
    hkitp5Dose: "hkitp5Dose",
    hkitp5Time: "hkitp5Time",
    hkitp5Why: "hkitp5Why",
    hkitp6Pill: "hkitp6Pill",
    hkitp6Dose: "hkitp6Dose",
    hkitp6Time: "hkitp6Time",
    hkitp6Why: "hkitp6Why",
    //gtp
    gtp1Pill: "gtp1Pill",
    gtp1Dose: "gtp1Dose",
    gtp1Time: "01/2012",
    gtp1Why: "gtp1Why",
    gtp2Pill: "gtp2Pill",
    gtp2Dose: "gtp2Dose",
    gtp2Time: "02/2012",
    gtp2Why: "gtp2Why",
    gtp3Pill: "gtp3Pill",
    gtp3Dose: "gtp3Dose",
    gtp3Time: "03/2012",
    gtp3Why: "gtp3Why",
    gtp4Pill: "gtp4Pill",
    gtp4Dose: "gtp4Dose",
    gtp4Time: "04/2012",
    gtp4Why: "gtp4Why",
    gtp5Pill: "gtp5Pill",
    gtp5Dose: "gtp5Dose",
    gtp5Time: "05/2012",
    gtp5Why: "gtp5Why",
    gtp6Pill: "gtp6Pill",
    gtp6Dose: "gtp6Dose",
    gtp6Time: "06/2012",
    gtp6Why: "gtp6Why",
    //gtp end
    pillEffect1: "evet",
    pillEffect1Desc: "bla bla",
    //BUNU TEMİZLEME !!!!!
    pillUse1: "hayır",
    pillUse2: "hayır",
    pillUse3: "hayır",
    akn15: "lt5",
    akn1Why: "bla bla",
    akn25: "gt5",
    akn2Why: "bla bla",
    akn35: "lt5",
    akn3Why: "bla bla",
    //BUNU TEMİZLEME !!!!!
    ABUse1: "hayır",
    ABUse1Desc: "bla bla xxxxxx",

    stk15: "lt5",
    stk1Why: "bla bla",
    stk25: "gt5",
    stk2Why: "bla bla",
    stk35: "gt5",
    stk3Why: "bla bla",
}


export const flow4FormInitialValues = {
    headAche: 0,
    headDizziness: 0,
    headNausea: 0,
    headSleeplessness: 0,
    eyeWatering: 0,
    eyeSwelling: 0,
    eyePuffiness: 0,
    eyeBlurryVision: 0,
    earItching: 0,
    earPain: 0,
    earDischarge: 0,
    earRinging: 0,
    noseCongestion: 0,
    noseSinus: 0,
    noseAllergy: 0,
    noseSneezing: 0,
    noseMucus: 0,
    mouthCough: 0,
    mouthCleaning: 0,
    mouthPain: 0,
    mouthSwelling: 0,
    mouthCotton: 0,
    skinAcne: 0,
    skinRash: 0,
    skinItching: 0,
    skinBaldness: 0,
    skinSweating: 0,
    heartIrregularity: 0,
    heartFast: 0,
    heartChestPain: 0,
    lungCongestion: 0,
    lungAsthma: 0,
    lungShortnessOfBreath: 0,
    lungBreathingDifficulties: 0,
    digestiveNausea: 0,
    digestiveDiarrhea: 0,
    digestiveConstipation: 0,
    digestiveBloating: 0,
    digestiveGas: 0,
    digestiveBurning: 0,
    digestiveStomachPain: 0,
    jointsPain: 0,
    jointsArthritis: 0,
    jointsStiffness: 0,
    jointsMusclePain: 0,
    jointsFatigue: 0,
    weightOvereating: 0,
    weightCraving: 0,
    weightObesity: 0,
    weightImpulseEating: 0,
    weightWaterRetention: 0,
    weightWeightLoss: 0,
    energyLethargy: 0,
    energyApathy: 0,
    energyHyperactivity: 0,
    energyRestlessness: 0,
    mindMemory: 0,
    mindUnderstanding: 0,
    mindConcentration: 0,
    mindPhysicalCoordination: 0,
    mindDecisionMaking: 0,
    mindDizziness: 0,
    mindSpeech: 0,
    mindLearning: 0,
    emotionalVibration: 0,
    emotionalObsession: 0,
    emotionalAngry: 0,
    emotionalDepression: 0,
    otherFrequentIllness: 0,
    otherFrequentUrination: 0,
    otherGenitalItching: 0,
}


export const flow5FormInitialValues = {
    headAche: 0,
    headDizziness: 0,
    headNausea: 0,
    headSleeplessness: 0,
    eyeWatering: 0,
    eyeSwelling: 0,
    eyePuffiness: 0,
    eyeBlurryVision: 0,
    earItching: 0,
    earPain: 0,
    earDischarge: 0,
    earRinging: 0,
    noseCongestion: 0,
    noseSinus: 0,
    noseAllergy: 0,
    noseSneezing: 0,
    noseMucus: 0,
    mouthCough: 0,
    mouthCleaning: 0,
    mouthPain: 0,
    mouthSwelling: 0,
    mouthCotton: 0,
    skinAcne: 0,
    skinRash: 0,
    skinItching: 0,
    skinBaldness: 0,
    skinSweating: 0,
    heartIrregularity: 0,
    heartFast: 0,
    heartChestPain: 0,
    lungCongestion: 0,
    lungAsthma: 0,
    lungShortnessOfBreath: 0,
    lungBreathingDifficulties: 0,
    digestiveNausea: 0,
    digestiveDiarrhea: 0,
    digestiveConstipation: 0,
    digestiveBloating: 0,
    digestiveGas: 0,
    digestiveBurning: 0,
    digestiveStomachPain: 0,
    jointsPain: 0,
    jointsArthritis: 0,
    jointsStiffness: 0,
    jointsMusclePain: 0,
    jointsFatigue: 0,
    weightOvereating: 0,
    weightCraving: 0,
    weightObesity: 0,
    weightImpulseEating: 0,
    weightWaterRetention: 0,
    weightWeightLoss: 0,
    energyLethargy: 0,
    energyApathy: 0,
    energyHyperactivity: 0,
    energyRestlessness: 0,
    mindMemory: 0,
    mindUnderstanding: 0,
    mindConcentration: 0,
    mindPhysicalCoordination: 0,
    mindDecisionMaking: 0,
    mindDizziness: 0,
    mindSpeech: 0,
    mindLearning: 0,
    emotionalVibration: 0,
    emotionalObsession: 0,
    emotionalAngry: 0,
    emotionalDepression: 0,
    otherFrequentIllness: 0,
    otherFrequentUrination: 0,
    otherGenitalItching: 0,
    textLast2Week: "ııı",
    textLifeStyleChange: "xx",
    textHaveAProblem: "yy",
    textSomethingElse: "zz",

}