import { text } from "node:stream/consumers";
import * as Yup from "yup";

export const multiSelectValidationSchema = Yup.array()
    .of(Yup.string())
    .required("Zorunlu alan")
    .min(1, "Zorunlu alan");
export const singleSelectValidationSchema =
    Yup.string().required("Zorunlu alan");
export const textValidationSchema = Yup.string().required("Zorunlu alan");


export const flow2FormValidationSchema = Yup.object({
    parrentTolarance: singleSelectValidationSchema,
    motherMilk: singleSelectValidationSchema,
    solidFood: singleSelectValidationSchema,
    babyAllergy: singleSelectValidationSchema,
    childFoodReact: singleSelectValidationSchema,
    childFoodAccess: singleSelectValidationSchema,
    childFoodDisorder: singleSelectValidationSchema,
    foodDisorder: textValidationSchema,
    favoriteFood: textValidationSchema,
    mostEatenFood: textValidationSchema,
    foodPreparedBy: textValidationSchema,
    foodPurchasedBy: textValidationSchema,
    cookingFrequency: textValidationSchema,
    mostNutritiousFood: textValidationSchema,
    leastNutritiousFood: textValidationSchema,
    extraInfo: textValidationSchema,
    purposeOfFinal: textValidationSchema,
});

export const flow1FormValidationSchema = Yup.object({
    //min >= 2 words required
    fullName: Yup.string()
        .required("Zorunlu alan") //min 2 max 3 words
        .matches(
            /^[a-zA-ZşŞıİçÇöÖüÜ]+(?:[\s-][a-zA-ZşŞıİçÇöÖüÜ]+){1,3}$/,
            "Geçerli bir isim giriniz"
        ),
    age: Yup.number().required("Zorunlu alan"),
    gender: Yup.string()
        .required("Zorunlu alan")
        .oneOf(["kadın", "erkek", "diger"], "Cinsiyet seçiniz"),
    email: Yup.string()
        .email("Geçerli bir email giriniz")
        .required("Zorunlu alan"),
    phone: textValidationSchema,
    country: textValidationSchema,
    city: textValidationSchema,
    identifiedDiseases: textValidationSchema,
    currentMedicationsAndTreatments: textValidationSchema,
    usedSupplementsAndTime: textValidationSchema,
    shortStory: textValidationSchema,
    purposeOfMeeting: textValidationSchema,
    meetingType: textValidationSchema,
});

export const flow3FormValidationSchema = Yup.object({
    name: textValidationSchema,
    age: textValidationSchema,
    date: textValidationSchema,
    birthDate: textValidationSchema,
    email: textValidationSchema,
    address: textValidationSchema,
    city: textValidationSchema,
    phoneCell: textValidationSchema,
    geneticHistory: textValidationSchema,
    geneticHistoryOther: Yup.string().when("geneticHistory", {
        is: (geneticHistory: string) => geneticHistory === "Diğer",
        then: textValidationSchema,
    }),
    lastHealt: textValidationSchema,
    emergencyContact: textValidationSchema,
    emergencyContactRelation: textValidationSchema,
    emergencyContactPhoneCell: textValidationSchema,
    whereDidYouHear: textValidationSchema,
    whereDidYouHearOther: Yup.string().when("whereDidYouHear", {
        is: (whereDidYouHear: string) => whereDidYouHear === "Diğer",
        then: textValidationSchema,
    }),
    currentDisease: Yup.array().of(
        Yup.object().shape({
            problem: Yup.string().required("Zorunlu"),
            severity: Yup.string().required("Zorunlu"),
            treatment: Yup.string().required("Zorunlu"),
            success: Yup.string().required("Zorunlu"),
        })
    ),
    allergies: Yup.array().of(
        Yup.object().shape({
            food: Yup.string().required("Zorunlu"),
            reaction: Yup.string().required("Zorunlu"),
        })
    ),
    sleepHours: textValidationSchema,
    sleepDifficulty: textValidationSchema,
    sleepQuality: textValidationSchema,
    sleepProblem: textValidationSchema,
    snore: textValidationSchema,
    wakeUp: textValidationSchema,
    sleepPills: textValidationSchema,
    sleepPillsDetail: Yup.string().when("sleepPills", {
        is: (sleepPills: string) => sleepPills === "evet",
        then: textValidationSchema,
    }),
    exerciseTable:textValidationSchema,
    exerciseRegimen:textValidationSchema,
    exerciseRegimenDesc:textValidationSchema,
    exerciseLater:textValidationSchema,
    exerciseLaterDesc:textValidationSchema,
    diet: Yup.array().of(
        textValidationSchema
    ),
    foodSensitivity: textValidationSchema,
    foodSensitivityDetail: Yup.string().when("foodSensitivity", {
        is: "evet",
        then: textValidationSchema
    }),
    foodAvoid: textValidationSchema,
    foodAvoidDetail: Yup.string().when("foodAvoid", {
        is: "evet",
        then: textValidationSchema
    }),
    foodsReaction: Yup.array().required("Bu alan zorunludur"),
    foodsReactionDetail: Yup.string().when("foodsReaction", {
        is: (val: any) => val.includes("diğer"),
        then: textValidationSchema
    }),
    foodsLike: textValidationSchema,
    foodsLikeDetail: Yup.string().when("foodsLike", {
        is: "evet",
        then: textValidationSchema
    }),
    threeMeal: textValidationSchema,
    threeMealDetail: Yup.string().when("threeMeal", {
        is: "hayır",
        then: textValidationSchema
    }),
    skipMeal: textValidationSchema,
    skipMealDetail: Yup.string().when("skipMeal", {
        is: "evet",
        then: textValidationSchema
    }),
    outsideMeal: textValidationSchema,
    lifestyleAboutEating: Yup.array().of(
        textValidationSchema
    ),
    currentDiet: Yup.array().of(
        textValidationSchema
    ),

    currentDietOther: textValidationSchema,
    breakfast:textValidationSchema,
    lunch:textValidationSchema,
    dinner:textValidationSchema,
    snacks:textValidationSchema,
    beverages:textValidationSchema,
    fruit:textValidationSchema,
    vegetable: textValidationSchema,
    legumes:textValidationSchema,
    redMeat:textValidationSchema,
    fish:textValidationSchema,
    dairyProducts:textValidationSchema,
    nutsAndSeeds:textValidationSchema,
    oil:textValidationSchema,
    cannedDrink:textValidationSchema,
    dessert:textValidationSchema,
    caffeinatedBeverage:textValidationSchema,
    caffeinatedBeverageYes:textValidationSchema,
    coffeQuantity:textValidationSchema,
    teaQuantity:textValidationSchema,
    carbonatedCoffeeQuantity:textValidationSchema,
    caffeineReaction:textValidationSchema,
    caffeineReactionDesc:textValidationSchema,
    caffeineSensation:Yup.array().of(
        textValidationSchema
    ),
    smoke:textValidationSchema,
    smokeType:Yup.array().of(
        textValidationSchema
    ),
    smokeQuantity:textValidationSchema,
    smokeYear:textValidationSchema,
    smokeBlock:textValidationSchema,
    smokeBlockDesc:textValidationSchema,
    oldSmoke:textValidationSchema,
    oldSmokeQuantity:textValidationSchema,
    oldSmokeYear:textValidationSchema,
    cigaretteSmoke:textValidationSchema,
    alcoholWeek:textValidationSchema,
    oldAlcohol:textValidationSchema,
    oldAlcoholProblems:textValidationSchema,
    oldAlcoholProblemsWhatTime:textValidationSchema,
    oldAlcoholProblemsDesc:textValidationSchema,
    oldAlcoholProblemsHelp:textValidationSchema,
    recreationalDrug:textValidationSchema,
    recreationalDrugDesc:textValidationSchema,
    inhaledSubstance:textValidationSchema,
    stress:textValidationSchema,
    copeWithStress:textValidationSchema,
    relaxationTechniques:textValidationSchema,
    relaxationTechniquesDesc:textValidationSchema,
    techniques:Yup.array().of(
        textValidationSchema
    ),
    techniquesDesc:textValidationSchema,
    consultancy:textValidationSchema,
    therapy:textValidationSchema,
    therapyDesc: textValidationSchema,
    molestation:textValidationSchema,
    maritalStatus:textValidationSchema,
    liveWith:textValidationSchema,
    job:textValidationSchema,
    oldJob:textValidationSchema,
    emotionalSupport:textValidationSchema,
    emotionalSupportSelect: Yup.array().of(
        textValidationSchema
    ),
    emotionalSupportOther:Yup.string().when("emotionalSupportSelect", {
        is: (val: any) => val.includes("diger"),
        then: textValidationSchema
    }),
    general:textValidationSchema,
    school:textValidationSchema,
    businessLife:textValidationSchema,
    socialLife:textValidationSchema,
    bestFriend:textValidationSchema,
    sexuality:textValidationSchema,
    position:textValidationSchema,
    withBoyFriendAndGirlFriend:textValidationSchema,
    children:textValidationSchema,
    parents:textValidationSchema,
    partner:textValidationSchema,
    birth:Yup.array().of(
        textValidationSchema
    ),
    birthComplication:textValidationSchema,
    birthComplicationDesc:textValidationSchema,


    solidFoods:textValidationSchema,
    wheat:textValidationSchema,
    dairy:textValidationSchema,
    avoidedFood:textValidationSchema,
    sugarOrSweet:textValidationSchema,
    silverMercuryFiller:textValidationSchema,
    silverMercuryFillerDesc: textValidationSchema,
    GoldFiller:textValidationSchema,
    GoldFillerDesc:textValidationSchema,
    rootCanalTreatment:textValidationSchema,
    rootCanalTreatmentDesc:textValidationSchema,
    Implant:textValidationSchema,
    ImplantDesc:textValidationSchema,
    platingMetal:textValidationSchema,
    platingMetalDesc:textValidationSchema,
    toothache:textValidationSchema,
    toothacheDesc:textValidationSchema,
    bleedingGums:textValidationSchema,
    bleedingGumsDesc:textValidationSchema,
    gumProblem:textValidationSchema,
    gumProblemDesc:textValidationSchema,
    chewingProblems:textValidationSchema,
    chewingProblemsDesc:textValidationSchema,
    otherDentalProblems:textValidationSchema,
    otherDentalProblemsDesc:textValidationSchema,
    removingYourMercuryFiller:textValidationSchema,
    removingYourMercuryFillerDesc:textValidationSchema,
    howManyFillersAsAChild:textValidationSchema,
    brushingTeeth:textValidationSchema,
    floss:textValidationSchema,
    affectsYouSignificantly:Yup.array().of(
        textValidationSchema
    ),
    affectsYouSignificantlyDesc:textValidationSchema,
    exposedToAtWorkOrAtHome:Yup.array().of(
        textValidationSchema
    ),
    exposedToAtWorkOrAtHomeDesc:textValidationSchema,
    significantExposureToHarmfulChemical:textValidationSchema,
    significantExposureToHarmfulChemicalDesc:textValidationSchema,
    petOrFarmAnimal:textValidationSchema,
    petOrFarmAnimalDesc:textValidationSchema,
    suitablePartsForYou:Yup.array().of(
        textValidationSchema
    ),
    suitablePartsForYouPeeDesc:textValidationSchema,
    suitablePartsForYouSexualDesc:textValidationSchema,
    psa:textValidationSchema,
    psaValue:textValidationSchema,
    otherTest:textValidationSchema,
    pregnancy:textValidationSchema,
    pregnancyCount:textValidationSchema,
    low:textValidationSchema,
    lowCount:textValidationSchema,
    abortion:textValidationSchema,
    abortionCount:textValidationSchema,
    livingChild:textValidationSchema,
    livingChildCount:textValidationSchema,
    naturalChildbirth:textValidationSchema,
    naturalChildbirthCount:textValidationSchema,
    cesareanDelivery:textValidationSchema,
    cesareanDeliveryCount:textValidationSchema,
    birthdayOnTheDay:textValidationSchema,
    birthdayOnTheDayCount:textValidationSchema,
    premature:textValidationSchema,
    prematureCount:textValidationSchema,
    bigbaby:textValidationSchema,
    bigbabyCount:textValidationSchema,
    smallbaby:textValidationSchema,
    smallbabyCount:textValidationSchema,
    postPregnancyProblems:textValidationSchema,
    postPregnancyProblemsDesc:textValidationSchema,

    //date alan
    firstMenstrualAge:textValidationSchema,
    lastMenstrualAge:textValidationSchema,


    menstruationInterval:textValidationSchema,
    menstrualPeriod:textValidationSchema,
    menstrualCramp:textValidationSchema,
    menstrualPain:textValidationSchema,
    menstrualProblems:textValidationSchema,
    menstrualProblemsDesc:textValidationSchema,
    lastMenstrualProblems:textValidationSchema,
    lastMenstrualProblemsDesc:textValidationSchema,
    hormonalBirthControl:textValidationSchema,
    hormonalBirthControlDesc:textValidationSchema,
    anotherMethod:textValidationSchema,
    anotherMethods:Yup.array().of(
        textValidationSchema
    ),
    IsMenopause:textValidationSchema,
    MenopauseLastedAge:textValidationSchema,
    surgicalMenopause:textValidationSchema,
    surgicalMenopauseDesc:textValidationSchema,
    menopauseComplaints:Yup.array().of(
        textValidationSchema
    ),
    hormoneTherapy:textValidationSchema,
    hormoneTherapyDesc:textValidationSchema,
    gynecologicalSymptoms:Yup.array().of(
        textValidationSchema
    ),
    gynecologicalSymptomsDesc:textValidationSchema,
    smearTest:textValidationSchema,
    smearTestResponse:textValidationSchema,
    mammographyTest:textValidationSchema,
    mammographyTestResponse:textValidationSchema,
    bone:textValidationSchema,
    boneResponse:textValidationSchema,
    anotherTest:textValidationSchema,
    anotherTestDesc:textValidationSchema,

    medicalResumeDigestionQuestion1:textValidationSchema,
    medicalResumeDigestionQuestion2:textValidationSchema,
    medicalResumeDigestionQuestion3:textValidationSchema,
    medicalResumeDigestionQuestion4:textValidationSchema,
    medicalResumeDigestionQuestion5:textValidationSchema,
    medicalResumeDigestionQuestion6:textValidationSchema,
    medicalResumeBreathingQuestion1:textValidationSchema,
    medicalResumeBreathingQuestion2:textValidationSchema,
    medicalResumeBreathingQuestion3:textValidationSchema,
    medicalResumeBreathingQuestion4:textValidationSchema,
    medicalResumeBreathingQuestion5:textValidationSchema,
    medicalResumeBreathingQuestion6:textValidationSchema,
    medicalResumeGenitalQuestion1:textValidationSchema,
    medicalResumeGenitalQuestion2:textValidationSchema,
    medicalResumeGenitalQuestion3:textValidationSchema,
    medicalResumeGenitalQuestion4:textValidationSchema,
    medicalResumeGenitalQuestion5:textValidationSchema,
    medicalResumeGenitalQuestion6:textValidationSchema,
    medicalResumeGenitalQuestion7:textValidationSchema,
    medicalResumeMetabolicQuestion1:textValidationSchema,
    medicalResumeMetabolicQuestion2:textValidationSchema,
    medicalResumeMetabolicQuestion3:textValidationSchema,
    medicalResumeMetabolicQuestion4:textValidationSchema,
    medicalResumeMetabolicQuestion5:textValidationSchema,
    medicalResumeMetabolicQuestion6:textValidationSchema,
    medicalResumeMetabolicQuestion7:textValidationSchema,
    medicalResumeInflammatoryQuestion1:textValidationSchema,
    medicalResumeInflammatoryQuestion2:textValidationSchema,
    medicalResumeInflammatoryQuestion3:textValidationSchema,
    medicalResumeInflammatoryQuestion4:textValidationSchema,
    medicalResumeInflammatoryQuestion5:textValidationSchema,
    medicalResumeInflammatoryQuestion6:textValidationSchema,
    medicalResumeInflammatoryQuestion7:textValidationSchema,
    medicalResumeInflammatoryQuestion8:textValidationSchema,
    medicalResumeInflammatoryQuestion9:textValidationSchema,
    medicalResumeMusculoskeletalQuestion1:textValidationSchema,
    medicalResumeMusculoskeletalQuestion2:textValidationSchema,
    medicalResumeMusculoskeletalQuestion3:textValidationSchema,
    medicalResumeLeatherQuestion1:textValidationSchema,
    medicalResumeLeatherQuestion2:textValidationSchema,
    medicalResumeLeatherQuestion3:textValidationSchema,
    medicalResumeLeatherQuestion4:textValidationSchema,
    medicalResumeHeartQuestion1:textValidationSchema,
    medicalResumeHeartQuestion2:textValidationSchema,
    medicalResumeHeartQuestion3:textValidationSchema,
    medicalResumeHeartQuestion4:textValidationSchema,
    medicalResumeHeartQuestion5:textValidationSchema,
    medicalResumeHeartQuestion6:textValidationSchema,
    medicalResumeHeartQuestion7:textValidationSchema,
    medicalResumeHeartQuestion8:textValidationSchema,
    medicalResumeHeartQuestion9:textValidationSchema,
    medicalResumeHeartQuestion10:textValidationSchema,
    medicalResumeNeurologicalQuestion1:textValidationSchema,
    medicalResumeNeurologicalQuestion2:textValidationSchema,
    medicalResumeNeurologicalQuestion3:textValidationSchema,
    medicalResumeNeurologicalQuestion4:textValidationSchema,
    medicalResumeNeurologicalQuestion5:textValidationSchema,
    medicalResumeNeurologicalQuestion6:textValidationSchema,
    medicalResumeNeurologicalQuestion7:textValidationSchema,
    medicalResumeNeurologicalQuestion8:textValidationSchema,
    medicalResumeNeurologicalQuestion9:textValidationSchema,
    medicalResumeNeurologicalQuestion10:textValidationSchema,
    medicalResumeCancerQuestion1:textValidationSchema,
    medicalResumeCancerQuestion2:textValidationSchema,
    medicalResumeCancerQuestion3:textValidationSchema,
    medicalResumeCancerQuestion4:textValidationSchema,
    medicalResumeCancerQuestion5:textValidationSchema,
    examinationOfSymptomsGeneralQuestion1:textValidationSchema,
    examinationOfSymptomsGeneralQuestion2:textValidationSchema,
    examinationOfSymptomsGeneralQuestion3:textValidationSchema,
    examinationOfSymptomsGeneralQuestion4:textValidationSchema,
    examinationOfSymptomsGeneralQuestion5:textValidationSchema,
    examinationOfSymptomsGeneralQuestion6:textValidationSchema,
    examinationOfSymptomsGeneralQuestion7:textValidationSchema,
    examinationOfSymptomsGeneralQuestion8:textValidationSchema,
    examinationOfSymptomsGeneralQuestion9:textValidationSchema,
    examinationOfSymptomsGeneralQuestion10:textValidationSchema,
    examinationOfSymptomsGeneralQuestion11:textValidationSchema,
    examinationOfSymptomsGeneralQuestion12:textValidationSchema,
    examinationOfSymptomsGeneralQuestion13:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion1:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion2:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion3:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion4:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion5:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion6:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion7:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion8:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion9:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion10:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion11:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion12:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion13:textValidationSchema,
    examinationOfSymptomsEyesAndEarQuestion14:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion1:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion2:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion3:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion4:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion5:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion6:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion7:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion8:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion9:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion10:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion11:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion12:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion13:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion14:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion15:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion16:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion17:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion18:textValidationSchema,
    examinationOfSymptomsSkeletonQuestion19:textValidationSchema,
    examinationOfSymptomsHeartQuestion1:textValidationSchema,
    examinationOfSymptomsHeartQuestion2:textValidationSchema,
    examinationOfSymptomsHeartQuestion3:textValidationSchema,
    examinationOfSymptomsHeartQuestion4:textValidationSchema,
    examinationOfSymptomsHeartQuestion5:textValidationSchema,
    examinationOfSymptomsHeartQuestion6:textValidationSchema,
    examinationOfSymptomsHeartQuestion7:textValidationSchema,
    examinationOfSymptomsHeartQuestion8:textValidationSchema,
    examinationOfSymptomsHeartQuestion9:textValidationSchema,
    examinationOfSymptomsHeartQuestion10:textValidationSchema,
    examinationOfSymptomsHeartQuestion11:textValidationSchema,
    examinationOfSymptomsPeeQuestion1:textValidationSchema,
    examinationOfSymptomsPeeQuestion2:textValidationSchema,
    examinationOfSymptomsPeeQuestion3:textValidationSchema,
    examinationOfSymptomsPeeQuestion4:textValidationSchema,
    examinationOfSymptomsPeeQuestion5:textValidationSchema,
    examinationOfSymptomsPeeQuestion6:textValidationSchema,
    examinationOfSymptomsPeeQuestion7:textValidationSchema,
    examinationOfSymptomsPeeQuestion8:textValidationSchema,
    examinationOfSymptomsPeeQuestion9:textValidationSchema,
    examinationOfSymptomsPeeQuestion10:textValidationSchema,
    examinationOfSymptomsEatingQuestion1:textValidationSchema,
    examinationOfSymptomsEatingQuestion2:textValidationSchema,
    examinationOfSymptomsEatingQuestion3:textValidationSchema,
    examinationOfSymptomsEatingQuestion4:textValidationSchema,
    examinationOfSymptomsEatingQuestion5:textValidationSchema,
    examinationOfSymptomsEatingQuestion6:textValidationSchema,
    examinationOfSymptomsEatingQuestion7:textValidationSchema,
    examinationOfSymptomsEatingQuestion8:textValidationSchema,
    examinationOfSymptomsEatingQuestion9:textValidationSchema,
    examinationOfSymptomsEatingQuestion10:textValidationSchema,
    examinationOfSymptomsEatingQuestion11:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion1:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion2:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion3:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion4:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion5:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion6:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion7:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion8:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion9:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion10:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion11:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion12:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion13:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion14:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion15:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion16:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion17:textValidationSchema,
    examinationOfSymptomsRespiratoryQuestion18:textValidationSchema,
    examinationOfSymptomsQuotesQuestion1:textValidationSchema,
    examinationOfSymptomsQuotesQuestion2:textValidationSchema,
    examinationOfSymptomsQuotesQuestion3:textValidationSchema,
    examinationOfSymptomsQuotesQuestion4:textValidationSchema,
    examinationOfSymptomsQuotesQuestion5:textValidationSchema,
    examinationOfSymptomsQuotesQuestion6:textValidationSchema,
    examinationOfSymptomsQuotesQuestion7:textValidationSchema,
    examinationOfSymptomsQuotesQuestion8:textValidationSchema,
    examinationOfSymptomsQuotesQuestion9:textValidationSchema,
    examinationOfSymptomsQuotesQuestion10:textValidationSchema,
    examinationOfSymptomsQuotesQuestion11:textValidationSchema,
    examinationOfSymptomsQuotesQuestion12:textValidationSchema,
    examinationOfSymptomsQuotesQuestion13:textValidationSchema,
    examinationOfSymptomsLymphNodesQuestion1:textValidationSchema,
    examinationOfSymptomsLymphNodesQuestion2:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion1:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion2:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion3:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion4:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion5:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion6:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion7:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion8:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion9:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion10:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion11:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion12:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion13:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion14:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion15:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion16:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion17:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion18:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion19:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion20:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion21:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion22:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion23:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion24:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion25:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion26:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion27:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion28:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion29:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion30:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion31:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion32:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion33:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion34:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion35:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion37:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion38:textValidationSchema,
    examinationOfSymptomsSkinDrynessQuestion39:textValidationSchema,
    examinationOfSymptomsDigestionQuestion1:textValidationSchema,
    examinationOfSymptomsDigestionQuestion2:textValidationSchema,
    examinationOfSymptomsDigestionQuestion3:textValidationSchema,
    examinationOfSymptomsDigestionQuestion4:textValidationSchema,
    examinationOfSymptomsDigestionQuestion5:textValidationSchema,
    examinationOfSymptomsDigestionQuestion6:textValidationSchema,
    examinationOfSymptomsDigestionQuestion7:textValidationSchema,
    examinationOfSymptomsDigestionQuestion8:textValidationSchema,
    examinationOfSymptomsDigestionQuestion9:textValidationSchema,
    examinationOfSymptomsDigestionQuestion10:textValidationSchema,
    examinationOfSymptomsDigestionQuestion11:textValidationSchema,
    examinationOfSymptomsDigestionQuestion12:textValidationSchema,
    examinationOfSymptomsDigestionQuestion13:textValidationSchema,
    examinationOfSymptomsDigestionQuestion14:textValidationSchema,
    examinationOfSymptomsDigestionQuestion15:textValidationSchema,
    examinationOfSymptomsDigestionQuestion16:textValidationSchema,
    examinationOfSymptomsDigestionQuestion17:textValidationSchema,
    examinationOfSymptomsDigestionQuestion18:textValidationSchema,
    examinationOfSymptomsDigestionQuestion19:textValidationSchema,
    examinationOfSymptomsDigestionQuestion20:textValidationSchema,
    examinationOfSymptomsDigestionQuestion21:textValidationSchema,
    examinationOfSymptomsDigestionQuestion22:textValidationSchema,
    examinationOfSymptomsDigestionQuestion23:textValidationSchema,
    examinationOfSymptomsDigestionQuestion24:textValidationSchema,
    examinationOfSymptomsDigestionQuestion25:textValidationSchema,
    examinationOfSymptomsDigestionQuestion26:textValidationSchema,
    examinationOfSymptomsDigestionQuestion27:textValidationSchema,
    examinationOfSymptomsDigestionQuestion28:textValidationSchema,
    examinationOfSymptomsDigestionQuestion29:textValidationSchema,
    examinationOfSymptomsDigestionQuestion30:textValidationSchema,
    examinationOfSymptomsDigestionQuestion31:textValidationSchema,
    examinationOfSymptomsDigestionQuestion32:textValidationSchema,
    examinationOfSymptomsDigestionQuestion33:textValidationSchema,
    examinationOfSymptomsDigestionQuestion34:textValidationSchema,
    examinationOfSymptomsDigestionQuestion35:textValidationSchema,
    examinationOfSymptomsDigestionQuestion36:textValidationSchema,
    examinationOfSymptomsDigestionQuestion37:textValidationSchema,
    examinationOfSymptomsDigestionQuestion38:textValidationSchema,
    examinationOfSymptomsNervesQuestion1:textValidationSchema,
    examinationOfSymptomsNervesQuestion2:textValidationSchema,
    examinationOfSymptomsNervesQuestion3:textValidationSchema,
    examinationOfSymptomsNervesQuestion4:textValidationSchema,
    examinationOfSymptomsNervesQuestion5:textValidationSchema,
    examinationOfSymptomsNervesQuestion6:textValidationSchema,
    examinationOfSymptomsNervesQuestion7:textValidationSchema,
    examinationOfSymptomsNervesQuestion8:textValidationSchema,
    examinationOfSymptomsNervesQuestion9:textValidationSchema,
    examinationOfSymptomsNervesQuestion10:textValidationSchema,
    examinationOfSymptomsNervesQuestion11:textValidationSchema,
    examinationOfSymptomsNervesQuestion12:textValidationSchema,
    examinationOfSymptomsNervesQuestion13:textValidationSchema,
    examinationOfSymptomsNervesQuestion14:textValidationSchema,
    examinationOfSymptomsNervesQuestion15:textValidationSchema,
    examinationOfSymptomsNervesQuestion16:textValidationSchema,
    examinationOfSymptomsNervesQuestion17:textValidationSchema,
    examinationOfSymptomsNervesQuestion18:textValidationSchema,
    examinationOfSymptomsNervesQuestion19:textValidationSchema,
    examinationOfSymptomsNervesQuestion20:textValidationSchema,
    examinationOfSymptomsNervesQuestion21:textValidationSchema,
    examinationOfSymptomsNervesQuestion22:textValidationSchema,
    examinationOfSymptomsNervesQuestion23:textValidationSchema,
    examinationOfSymptomsNervesQuestion24:textValidationSchema,
    examinationOfSymptomsNervesQuestion25:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion1:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion2:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion3:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion4:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion5:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion6:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion7:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion8:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion9:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion10:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion11:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion12:textValidationSchema,
    examinationOfSymptomsItchySkinQuestion13:textValidationSchema,
    examinationOfSymptomsMaleReproductionQuestion1:textValidationSchema,
    examinationOfSymptomsMaleReproductionQuestion2:textValidationSchema,
    examinationOfSymptomsMaleReproductionQuestion3:textValidationSchema,
    examinationOfSymptomsMaleReproductionQuestion4:textValidationSchema,
    examinationOfSymptomsMaleReproductionQuestion5:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion1:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion2:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion3:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion4:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion5:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion6:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion7:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion8:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion9:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion10:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion11:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion12:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion13:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion14:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion15:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion16:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion17:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion18:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion19:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion20:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion21:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion22:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion23:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion24:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion25:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion26:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion27:textValidationSchema,
    examinationOfSymptomsFemaleReproductionQuestion28:textValidationSchema,
    nutritionReplacement:textValidationSchema,
    nutritionalSupplement:textValidationSchema,
    foodTracking:textValidationSchema,
    changeLifestyle:textValidationSchema,
    relaxationTechnique:textValidationSchema,
    regularExercise:textValidationSchema,
    trustYourself:textValidationSchema,
    distrustDesc:textValidationSchema,
    familySupport:textValidationSchema,
    externalSupport:textValidationSchema,
    comments:textValidationSchema,
    healthGoalsQuestion9:textValidationSchema





    













})